afk.afk.channel=19
afk.ignored.channels=20,31,11,12,26,13,19,20
afk.ignored.groups=18,
afk.max.idle.ms=600000
afk.sleep.ms=60000
auth.ignore=false
bot.debug=false
bot.nickname=AdminBot
trollmove.ignored.channels=1,2,3
trollmove.ignored.clients=4,5,6
trollmove.ignored.groups=7,8,9
wordfilter.enabled=true
